export const TUTORIAL_KEYS = {
  principal: "correAquiTutorialPrincipalConcluido",
  cliente: "correAquiTutorialClienteConcluido",
  clientePulado: "correAquiTutorialClientePulado",
  clienteConcluidoEm: "correAquiTutorialClienteConcluidoEm",
  trabalhar: "correAquiTutorialTrabalharConcluido",
  trabalharPulado: "correAquiTutorialTrabalharPulado",
  trabalharConcluidoEm: "correAquiTutorialTrabalharConcluidoEm",
  dicaChat: "correAquiDicaChatVista",
  dicaPedido: "correAquiDicaPedidoVista",
  dicaAceite: "correAquiDicaAceiteVista",
  dicaPortfolio: "correAquiDicaPortfolioVista",
  dicaReputacao: "correAquiDicaReputacaoVista",
  dicaProgresso: "correAquiDicaProgressoVista",
}

export const TUTORIAL_EVENTS = {
  action: "corre-aqui:tutorial-action",
}

export const TUTORIAL_ACTIONS = {
  showClientHome: "show-client-home",
  showClientProfessionals: "show-client-professionals",
  showClientChatAccess: "show-client-chat-access",
  showClientProfileAccess: "show-client-profile-access",
  showWorkerOrders: "show-worker-orders",
  showWorkerCategories: "show-worker-categories",
  showWorkerChatAccess: "show-worker-chat-access",
  openProfessionalProfile: "open-professional-profile",
  openPortfolio: "open-portfolio",
  openReputation: "open-reputation",
  cleanupTutorialViews: "cleanup-tutorial-views",
}

export const TUTORIAL_FLOWS = {
  cliente: {
    id: "cliente",
    title: "Tutorial do Cliente",
    completionKey: TUTORIAL_KEYS.cliente,
    steps: [
      {
        id: "modo",
        route: "/",
        target: "modo",
        title: "Escolha de modo",
        text: "Escolha Quero contratar para usar o app como cliente sem criar perfil profissional publico.",
        placement: "bottom",
        interaction: "none",
        allowInformativeFallback: false,
      },
      {
        id: "mapa",
        route: "/cliente",
        target: "mapa",
        title: "Mapa",
        text: "Aqui voce encontra profissionais e atendimentos proximos da sua localizacao.",
        prepare: [TUTORIAL_ACTIONS.showClientHome],
        placement: "bottom",
        interaction: "none",
        allowInformativeFallback: false,
      },
      {
        id: "criar-pedido",
        route: "/cliente",
        target: "criar-pedido",
        title: "Criar pedido",
        text: "Toque aqui para criar um pedido. Voce pode escrever normalmente ou usar a IA para ajudar.",
        prepare: [TUTORIAL_ACTIONS.showClientHome],
        placement: "top",
        interaction: "none",
        allowInformativeFallback: false,
      },
      {
        id: "profissionais",
        route: "/cliente",
        target: "profissionais",
        title: "Profissionais",
        text: "E aqui que voce encontra profissionais, compara avaliacoes, distancia, experiencia e portfolio.",
        prepare: [TUTORIAL_ACTIONS.showClientProfessionals],
        placement: "top",
        interaction: "none",
        allowInformativeFallback: false,
      },
      {
        id: "chat",
        route: "/cliente",
        target: "chat",
        title: "Chat",
        text: "Este e o acesso para suas conversas. Combine valor, horario, localizacao e detalhes por aqui.",
        prepare: [TUTORIAL_ACTIONS.showClientChatAccess],
        placement: "top",
        interaction: "none",
        allowInformativeFallback: true,
      },
      {
        id: "progresso",
        target: "progresso",
        title: "Progresso do atendimento",
        text: "Acompanhe cada etapa do atendimento: Aceito, Em andamento, Chegou e Finalizado.",
        interaction: "none",
        allowInformativeFallback: true,
        informativeWhenMissing: true,
      },
      {
        id: "confirmacao-final",
        target: "confirmacao-final",
        title: "Confirmacao da conclusao",
        text: "Quando o profissional solicitar a conclusao, confirme se o servico foi realmente finalizado.",
        interaction: "none",
        allowInformativeFallback: true,
        informativeWhenMissing: true,
      },
      {
        id: "perfil",
        route: "/cliente",
        target: "perfil",
        title: "Perfil e historico",
        text: "Este e o botao Perfil. Por ele voce acessa pedidos, historico, configuracoes e ajuda.",
        prepare: [TUTORIAL_ACTIONS.showClientProfileAccess],
        placement: "left",
        interaction: "none",
        allowInformativeFallback: false,
      },
    ],
  },
  trabalhar: {
    id: "trabalhar",
    title: "Tutorial de Trabalhar",
    completionKey: TUTORIAL_KEYS.trabalhar,
    steps: [
      {
        id: "modo-trabalhar",
        route: "/",
        target: "modo-trabalhar",
        title: "Modo Trabalhar",
        text: "Escolha Trabalhar para criar sua ficha publica de trabalho antes de aparecer para clientes.",
        placement: "bottom",
        interaction: "none",
        allowInformativeFallback: false,
      },
      {
        id: "perfil-profissional",
        route: "/corre",
        target: "perfil-profissional",
        title: "Perfil profissional",
        text: "Esta e a area da sua ficha publica. Complete servicos, portfolio e disponibilidade para transmitir mais confianca.",
        prepare: [TUTORIAL_ACTIONS.openProfessionalProfile],
        placement: "left",
        interaction: "none",
        allowInformativeFallback: false,
      },
      {
        id: "categorias",
        route: "/corre",
        target: "categorias",
        title: "Categorias",
        text: "Aqui ficam as categorias dos pedidos. Use esta area para filtrar os trabalhos que voce quer atender.",
        prepare: [TUTORIAL_ACTIONS.showWorkerCategories],
        placement: "bottom",
        interaction: "none",
        allowInformativeFallback: false,
      },
      {
        id: "portfolio",
        route: "/corre",
        target: "portfolio",
        title: "Portfolio",
        text: "Esta e sua vitrine. Cadastre fotos, servicos e valores para mostrar seu trabalho aos clientes.",
        prepare: [TUTORIAL_ACTIONS.openPortfolio],
        placement: "left",
        interaction: "none",
        allowInformativeFallback: true,
        informativeWhenMissing: true,
      },
      {
        id: "lista-pedidos",
        route: "/corre",
        target: "lista-pedidos",
        title: "Lista de pedidos",
        text: "E aqui que seus pedidos proximos aparecem. Mesmo vazia, esta lista mostra onde os trabalhos chegam.",
        prepare: [TUTORIAL_ACTIONS.showWorkerOrders],
        placement: "top",
        interaction: "none",
        allowInformativeFallback: false,
      },
      {
        id: "aceitar-pedido",
        route: "/corre",
        target: "aceitar-pedido",
        title: "Aceitar pedido",
        text: "Aceite somente pedidos que voce realmente podera realizar.",
        prepare: [TUTORIAL_ACTIONS.showWorkerOrders],
        placement: "top",
        interaction: "none",
        allowInformativeFallback: true,
        informativeWhenMissing: true,
      },
      {
        id: "chat",
        route: "/corre",
        target: "chat",
        title: "Chat",
        text: "Este e o acesso ao chat profissional. Combine valor, horario, localizacao e detalhes antes de comecar.",
        prepare: [TUTORIAL_ACTIONS.showWorkerChatAccess],
        placement: "top",
        interaction: "none",
        allowInformativeFallback: true,
      },
      {
        id: "progresso",
        route: "/corre",
        target: "progresso",
        title: "Progresso",
        text: "Durante o atendimento, atualize as etapas: Iniciar atendimento, Cheguei e Solicitar conclusao.",
        interaction: "none",
        allowInformativeFallback: true,
        informativeWhenMissing: true,
      },
      {
        id: "reputacao",
        route: "/corre",
        target: "reputacao",
        title: "Construa sua reputação",
        text: "Avaliações reais, serviços concluídos e bom atendimento ajudam clientes a confiar no seu trabalho.",
        prepare: [TUTORIAL_ACTIONS.openReputation],
        placement: "left",
        interaction: "none",
        allowInformativeFallback: true,
        informativeWhenMissing: true,
      },
    ],
  },
}

export const ASSISTANT_TOPICS = [
  {
    id: "pedido",
    label: "Como criar um pedido",
    flow: "cliente",
    target: "criar-pedido",
  },
  {
    id: "aceitar",
    label: "Como aceitar um atendimento",
    flow: "trabalhar",
    target: "aceitar-pedido",
  },
  {
    id: "chat",
    label: "Como usar o chat",
    flow: "cliente",
    target: "chat",
  },
  {
    id: "progresso",
    label: "Como funciona o progresso",
    flow: "cliente",
    target: "progresso",
  },
  {
    id: "portfolio",
    label: "Como funciona o portfolio",
    flow: "trabalhar",
    target: "portfolio",
  },
  {
    id: "reputacao",
    label: "Como construir minha reputação",
    flow: "trabalhar",
    target: "reputacao",
  },
]

export function getFlowForMode(mode) {
  return String(mode || "").toLowerCase() === "corre" ? "trabalhar" : "cliente"
}

export function findStepIndex(flowId, targetOrStepId) {
  const flow = TUTORIAL_FLOWS[flowId]
  if (!flow) return 0
  const index = flow.steps.findIndex((step) => step.id === targetOrStepId || step.target === targetOrStepId)
  return index >= 0 ? index : 0
}
